//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sweco.SIF.LayerManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-T-")]
        public string REGISTopFilePatternString {
            get {
                return ((string)(this["REGISTopFilePatternString"]));
            }
            set {
                this["REGISTopFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-B-")]
        public string REGISBotFilePatternString {
            get {
                return ((string)(this["REGISBotFilePatternString"]));
            }
            set {
                this["REGISBotFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-kD-")]
        public string REGISkDFilePatternString {
            get {
                return ((string)(this["REGISkDFilePatternString"]));
            }
            set {
                this["REGISkDFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-C-")]
        public string REGISCFilePatternString {
            get {
                return ((string)(this["REGISCFilePatternString"]));
            }
            set {
                this["REGISCFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-kh-")]
        public string REGISKHFilePatternString {
            get {
                return ((string)(this["REGISKHFilePatternString"]));
            }
            set {
                this["REGISKHFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-kv-")]
        public string REGISKVFilePatternString {
            get {
                return ((string)(this["REGISKVFilePatternString"]));
            }
            set {
                this["REGISKVFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TOP")]
        public string TopFilePrefix {
            get {
                return ((string)(this["TopFilePrefix"]));
            }
            set {
                this["TopFilePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BOT")]
        public string BotFilePrefix {
            get {
                return ((string)(this["BotFilePrefix"]));
            }
            set {
                this["BotFilePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kD")]
        public string kDFilePrefix {
            get {
                return ((string)(this["kDFilePrefix"]));
            }
            set {
                this["kDFilePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string CFilePrefix {
            get {
                return ((string)(this["CFilePrefix"]));
            }
            set {
                this["CFilePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KHV")]
        public string KHVFilePrefix {
            get {
                return ((string)(this["KHVFilePrefix"]));
            }
            set {
                this["KHVFilePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KVV")]
        public string KVVFilePrefix {
            get {
                return ((string)(this["KVVFilePrefix"]));
            }
            set {
                this["KVVFilePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DIKTE")]
        public string ThicknessFilePrefix {
            get {
                return ((string)(this["ThicknessFilePrefix"]));
            }
            set {
                this["ThicknessFilePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TOP*")]
        public string iMODTOPFilePatternString {
            get {
                return ((string)(this["iMODTOPFilePatternString"]));
            }
            set {
                this["iMODTOPFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BOT*")]
        public string iMODBOTFilePatternString {
            get {
                return ((string)(this["iMODBOTFilePatternString"]));
            }
            set {
                this["iMODBOTFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kD*")]
        public string iMODkDFilePatternString {
            get {
                return ((string)(this["iMODkDFilePatternString"]));
            }
            set {
                this["iMODkDFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C*")]
        public string iMODCFilePatternString {
            get {
                return ((string)(this["iMODCFilePatternString"]));
            }
            set {
                this["iMODCFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KH*")]
        public string iMODKHVFilePatternString {
            get {
                return ((string)(this["iMODKHVFilePatternString"]));
            }
            set {
                this["iMODKHVFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KV*")]
        public string iMODKVVFilePatternString {
            get {
                return ((string)(this["iMODKVVFilePatternString"]));
            }
            set {
                this["iMODKVVFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KVA*")]
        public string iMODKVAFilePatternString {
            get {
                return ((string)(this["iMODKVAFilePatternString"]));
            }
            set {
                this["iMODKVAFilePatternString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TOP")]
        public string TOPSubdirname {
            get {
                return ((string)(this["TOPSubdirname"]));
            }
            set {
                this["TOPSubdirname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BOT")]
        public string BOTSubdirname {
            get {
                return ((string)(this["BOTSubdirname"]));
            }
            set {
                this["BOTSubdirname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kD")]
        public string kDSubdirname {
            get {
                return ((string)(this["kDSubdirname"]));
            }
            set {
                this["kDSubdirname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string CSubdirName {
            get {
                return ((string)(this["CSubdirName"]));
            }
            set {
                this["CSubdirName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KHV")]
        public string KHVSubdirname {
            get {
                return ((string)(this["KHVSubdirname"]));
            }
            set {
                this["KHVSubdirname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KVV")]
        public string KVVSubdirname {
            get {
                return ((string)(this["KVVSubdirname"]));
            }
            set {
                this["KVVSubdirname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DIKTE")]
        public string ThicknessSubdirname {
            get {
                return ((string)(this["ThicknessSubdirname"]));
            }
            set {
                this["ThicknessSubdirname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mismatch")]
        public string MismatchSubdirname {
            get {
                return ((string)(this["MismatchSubdirname"]));
            }
            set {
                this["MismatchSubdirname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("modelchecks")]
        public string ModelchecksSubdirname {
            get {
                return ((string)(this["ModelchecksSubdirname"]));
            }
            set {
                this["ModelchecksSubdirname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DefaultKDValue {
            get {
                return ((float)(this["DefaultKDValue"]));
            }
            set {
                this["DefaultKDValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float DefaultCValue {
            get {
                return ((float)(this["DefaultCValue"]));
            }
            set {
                this["DefaultCValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float DefaultKHValue {
            get {
                return ((float)(this["DefaultKHValue"]));
            }
            set {
                this["DefaultKHValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public float DefaultKVValue {
            get {
                return ((float)(this["DefaultKVValue"]));
            }
            set {
                this["DefaultKVValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public float DefaultKVAValue {
            get {
                return ((float)(this["DefaultKVAValue"]));
            }
            set {
                this["DefaultKVAValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public float LevelTolerance {
            get {
                return ((float)(this["LevelTolerance"]));
            }
            set {
                this["LevelTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public float MissingThicknessTolerance {
            get {
                return ((float)(this["MissingThicknessTolerance"]));
            }
            set {
                this["MissingThicknessTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxWarningMessageCount {
            get {
                return ((int)(this["MaxWarningMessageCount"]));
            }
            set {
                this["MaxWarningMessageCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsInconsistentNoDataChecked {
            get {
                return ((bool)(this["IsInconsistentNoDataChecked"]));
            }
            set {
                this["IsInconsistentNoDataChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WVP")]
        public string REGISAquiferAbbr {
            get {
                return ((string)(this["REGISAquiferAbbr"]));
            }
            set {
                this["REGISAquiferAbbr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SDL")]
        public string REGISAquitardAbbr {
            get {
                return ((string)(this["REGISAquitardAbbr"]));
            }
            set {
                this["REGISAquitardAbbr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-kd-verz")]
        public string REGISkDFilePostfix {
            get {
                return ((string)(this["REGISkDFilePostfix"]));
            }
            set {
                this["REGISkDFilePostfix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-c")]
        public string REGISCFilePostfix {
            get {
                return ((string)(this["REGISCFilePostfix"]));
            }
            set {
                this["REGISCFilePostfix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-d-c")]
        public string REGISThicknessPostfix {
            get {
                return ((string)(this["REGISThicknessPostfix"]));
            }
            set {
                this["REGISThicknessPostfix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsInconsistentModelAborted {
            get {
                return ((bool)(this["IsInconsistentModelAborted"]));
            }
            set {
                this["IsInconsistentModelAborted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SDL")]
        public string OutputAquitardLayerPostfix {
            get {
                return ((string)(this["OutputAquitardLayerPostfix"]));
            }
            set {
                this["OutputAquitardLayerPostfix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L")]
        public string OutputAquiferLayerPostfix {
            get {
                return ((string)(this["OutputAquiferLayerPostfix"]));
            }
            set {
                this["OutputAquiferLayerPostfix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L")]
        public string OutputLayerPostfix {
            get {
                return ((string)(this["OutputLayerPostfix"]));
            }
            set {
                this["OutputLayerPostfix"] = value;
            }
        }
    }
}
